unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

set nocompatible
set number
set title
set ruler
set showcmd
set showmatch
set laststatus=2
set hlsearch
set incsearch
set autoindent
set expandtab
set tabstop=2
"set <xUp>=OA
"set <xDown>=OB
"set <xRight>=OC
"set <xLeft>=OD
